/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;
import java.util.*;

/**
 *
 * @author aissami
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bstock = new javax.swing.JButton();
        Bclient = new javax.swing.JButton();
        Bpersonnel = new javax.swing.JButton();
        Bpointvente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Bstock.setBackground(new java.awt.Color(255, 255, 255));
        Bstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/b.stock.png"))); // NOI18N

        Bclient.setBackground(new java.awt.Color(255, 255, 255));
        Bclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/b.client.png"))); // NOI18N
        Bclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclientActionPerformed(evt);
            }
        });

        Bpersonnel.setBackground(new java.awt.Color(255, 255, 255));
        Bpersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/b.personnel.png"))); // NOI18N

        Bpointvente.setBackground(new java.awt.Color(255, 255, 255));
        Bpointvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/b.point vente.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bclient)
                            .addComponent(Bstock)
                            .addComponent(Bpersonnel)
                            .addComponent(Bpointvente))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(Bstock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bclient)
                .addGap(18, 18, 18)
                .addComponent(Bpersonnel)
                .addGap(18, 18, 18)
                .addComponent(Bpointvente)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclientActionPerformed
        // TODO add your handling code here:
        GestionClients Cl = new GestionClients();
        this.setVisible(false);
        Cl.setVisible(true);
    }//GEN-LAST:event_BclientActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclient;
    private javax.swing.JButton Bpersonnel;
    private javax.swing.JButton Bpointvente;
    private javax.swing.JButton Bstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
